(cl:in-package ublox_msgs-msg)
(cl:export '(VERSION-VAL
          VERSION
          MASK1-VAL
          MASK1
          MASK2-VAL
          MASK2
          RESERVED1-VAL
          RESERVED1
          MINSVS-VAL
          MINSVS
          MAXSVS-VAL
          MAXSVS
          MINCNO-VAL
          MINCNO
          RESERVED2-VAL
          RESERVED2
          INIFIX3D-VAL
          INIFIX3D
          RESERVED3-VAL
          RESERVED3
          ACKAIDING-VAL
          ACKAIDING
          WKNROLLOVER-VAL
          WKNROLLOVER
          SIGATTENCOMPMODE-VAL
          SIGATTENCOMPMODE
          RESERVED4-VAL
          RESERVED4
          USEPPP-VAL
          USEPPP
          AOPCFG-VAL
          AOPCFG
          RESERVED5-VAL
          RESERVED5
          AOPORBMAXERR-VAL
          AOPORBMAXERR
          RESERVED6-VAL
          RESERVED6
          USEADR-VAL
          USEADR
))