(cl:in-package ublox_msgs-msg)
(cl:export '(ITOW-VAL
          ITOW
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MIN-VAL
          MIN
          SEC-VAL
          SEC
          VALID-VAL
          VALID
          NANO-VAL
          NANO
          GPSFIX-VAL
          GPSFIX
          FLAGS-VAL
          FLAGS
          RESERVED0-VAL
          RESERVED0
          LON-VAL
          LON
          LAT-VAL
          LAT
          HEIGHT-VAL
          HEIGHT
          HMSL-VAL
          HMSL
          GSPEED-VAL
          GSPEED
          SPEED-VAL
          SPEED
          HEADMOT-VAL
          HEADMOT
          HEADVEH-VAL
          HEADVEH
          HACC-VAL
          HACC
          VACC-VAL
          VACC
          SACC-VAL
          SACC
          HEADACC-VAL
          HEADACC
          RESERVED1-VAL
          RESERVED1
))