(cl:in-package ublox_msgs-msg)
(cl:export '(ITOW-VAL
          ITOW
          FTOW-VAL
          FTOW
          WEEK-VAL
          WEEK
          GPSFIX-VAL
          GPSFIX
          FLAGS-VAL
          FLAGS
          ECEFX-VAL
          ECEFX
          ECEFY-VAL
          ECEFY
          ECEFZ-VAL
          ECEFZ
          PACC-VAL
          PACC
          ECEFVX-VAL
          ECEFVX
          ECEFVY-VAL
          ECEFVY
          ECEFVZ-VAL
          ECEFVZ
          SACC-VAL
          SACC
          PDOP-VAL
          PDOP
          RESERVED1-VAL
          RESERVED1
          NUMSV-VAL
          NUMSV
          RESERVED2-VAL
          RESERVED2
))