(cl:in-package ublox_msgs-msg)
(cl:export '(TYPE-VAL
          TYPE
          VERSION-VAL
          VERSION
          SVID-VAL
          SVID
          RESERVED0-VAL
          RESERVED0
          IODNAV-VAL
          IODNAV
          DELTAN-VAL
          DELTAN
          M0-VAL
          M0
          E-VAL
          E
          SQRTA-VAL
          SQRTA
          OMEGA0-VAL
          OMEGA0
          I0-VAL
          I0
          OMEGA-VAL
          OMEGA
          OMEGADOT-VAL
          OMEGADOT
          IDOT-VAL
          IDOT
          CUC-VAL
          CUC
          CUS-VAL
          CUS
          CRC-VAL
          CRC
          CRS-VAL
          CRS
          CIC-VAL
          CIC
          CIS-VAL
          CIS
          TOE-VAL
          TOE
          AF0-VAL
          AF0
          AF1-VAL
          AF1
          AF2-VAL
          AF2
          SISAINDEXE1E5B-VAL
          SISAINDEXE1E5B
          TOC-VAL
          TOC
          BGDE1E5B-VAL
          BGDE1E5B
          RESERVED1-VAL
          RESERVED1
          HEALTHE1B-VAL
          HEALTHE1B
          DATAVALIDITYE1B-VAL
          DATAVALIDITYE1B
          HEALTHE5B-VAL
          HEALTHE5B
          DATAVALIDITYE5B-VAL
          DATAVALIDITYE5B
          RESERVED2-VAL
          RESERVED2
))