(cl:in-package ublox_msgs-msg)
(cl:export '(MASK-VAL
          MASK
          DYNMODEL-VAL
          DYNMODEL
          FIXMODE-VAL
          FIXMODE
          FIXEDALT-VAL
          FIXEDALT
          FIXEDALTVAR-VAL
          FIXEDALTVAR
          MINELEV-VAL
          MINELEV
          DRLIMIT-VAL
          DRLIMIT
          PDOP-VAL
          PDOP
          TDOP-VAL
          TDOP
          PACC-VAL
          PACC
          TACC-VAL
          TACC
          STATICHOLDTHRESH-VAL
          STATICHOLDTHRESH
          DGNSSTIMEOUT-VAL
          DGNSSTIMEOUT
          CNOTHRESHNUMSVS-VAL
          CNOTHRESHNUMSVS
          CNOTHRESH-VAL
          CNOTHRESH
          RESERVED1-VAL
          RESERVED1
          STATICHOLDMAXDIST-VAL
          STATICHOLDMAXDIST
          UTCSTANDARD-VAL
          UTCSTANDARD
          RESERVED2-VAL
          RESERVED2
))