(cl:in-package ublox_msgs-msg)
(cl:export '(VERSION-VAL
          VERSION
          RESERVED0-VAL
          RESERVED0
          REFSTATIONID-VAL
          REFSTATIONID
          ITOW-VAL
          ITOW
          RELPOSN-VAL
          RELPOSN
          RELPOSE-VAL
          RELPOSE
          RELPOSD-VAL
          RELPOSD
          RELPOSHPN-VAL
          RELPOSHPN
          RELPOSHPE-VAL
          RELPOSHPE
          RELPOSHPD-VAL
          RELPOSHPD
          RESERVED1-VAL
          RESERVED1
          ACCN-VAL
          ACCN
          ACCE-VAL
          ACCE
          ACCD-VAL
          ACCD
          FLAGS-VAL
          FLAGS
))