(cl:in-package ublox_msgs-msg)
(cl:export '(ITOW-VAL
          ITOW
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MIN-VAL
          MIN
          SEC-VAL
          SEC
          VALID-VAL
          VALID
          TACC-VAL
          TACC
          NANO-VAL
          NANO
          FIXTYPE-VAL
          FIXTYPE
          FLAGS-VAL
          FLAGS
          FLAGS2-VAL
          FLAGS2
          NUMSV-VAL
          NUMSV
          LON-VAL
          LON
          LAT-VAL
          LAT
          HEIGHT-VAL
          HEIGHT
          HMSL-VAL
          HMSL
          HACC-VAL
          HACC
          VACC-VAL
          VACC
          VELN-VAL
          VELN
          VELE-VAL
          VELE
          VELD-VAL
          VELD
          GSPEED-VAL
          GSPEED
          HEADING-VAL
          HEADING
          SACC-VAL
          SACC
          HEADACC-VAL
          HEADACC
          PDOP-VAL
          PDOP
          RESERVED1-VAL
          RESERVED1
          HEADVEH-VAL
          HEADVEH
          MAGDEC-VAL
          MAGDEC
          MAGACC-VAL
          MAGACC
))