(cl:in-package ublox_msgs-msg)
(cl:export '(PRMES-VAL
          PRMES
          CPMES-VAL
          CPMES
          DOMES-VAL
          DOMES
          GNSSID-VAL
          GNSSID
          SVID-VAL
          SVID
          RESERVED0-VAL
          RESERVED0
          FREQID-VAL
          FREQID
          LOCKTIME-VAL
          LOCKTIME
          CNO-VAL
          CNO
          PRSTDEV-VAL
          PRSTDEV
          CPSTDEV-VAL
          CPSTDEV
          DOSTDEV-VAL
          DOSTDEV
          TRKSTAT-VAL
          TRKSTAT
          RESERVED1-VAL
          RESERVED1
))