(cl:in-package ublox_msgs-msg)
(cl:export '(PINSEL-VAL
          PINSEL
          PINBANK-VAL
          PINBANK
          PINDIR-VAL
          PINDIR
          PINVAL-VAL
          PINVAL
          NOISEPERMS-VAL
          NOISEPERMS
          AGCCNT-VAL
          AGCCNT
          ASTATUS-VAL
          ASTATUS
          APOWER-VAL
          APOWER
          FLAGS-VAL
          FLAGS
          RESERVED0-VAL
          RESERVED0
          USEDMASK-VAL
          USEDMASK
          VP-VAL
          VP
          JAMIND-VAL
          JAMIND
          RESERVED1-VAL
          RESERVED1
          PINIRQ-VAL
          PINIRQ
          PULLH-VAL
          PULLH
          PULLL-VAL
          PULLL
))