(cl:in-package ublox_msgs-msg)
(cl:export '(VERSION-VAL
          VERSION
          RESERVED0-VAL
          RESERVED0
          ITOW-VAL
          ITOW
          DUR-VAL
          DUR
          MEANX-VAL
          MEANX
          MEANY-VAL
          MEANY
          MEANZ-VAL
          MEANZ
          MEANXHP-VAL
          MEANXHP
          MEANYHP-VAL
          MEANYHP
          MEANZHP-VAL
          MEANZHP
          RESERVED1-VAL
          RESERVED1
          MEANACC-VAL
          MEANACC
          OBS-VAL
          OBS
          VALID-VAL
          VALID
          ACTIVE-VAL
          ACTIVE
          RESERVED3-VAL
          RESERVED3
))