(cl:in-package ublox_msgs-msg)
(cl:export '(HEALTH-VAL
          HEALTH
          UTCA0-VAL
          UTCA0
          UTCA1-VAL
          UTCA1
          UTCTOW-VAL
          UTCTOW
          UTCWNT-VAL
          UTCWNT
          UTCLS-VAL
          UTCLS
          UTCWNF-VAL
          UTCWNF
          UTCDN-VAL
          UTCDN
          UTCLSF-VAL
          UTCLSF
          UTCSPARE-VAL
          UTCSPARE
          KLOBA0-VAL
          KLOBA0
          KLOBA1-VAL
          KLOBA1
          KLOBA2-VAL
          KLOBA2
          KLOBA3-VAL
          KLOBA3
          KLOBB0-VAL
          KLOBB0
          KLOBB1-VAL
          KLOBB1
          KLOBB2-VAL
          KLOBB2
          KLOBB3-VAL
          KLOBB3
          FLAGS-VAL
          FLAGS
))