(cl:in-package ublox_msgs-msg)
(cl:export '(VERSION-VAL
          VERSION
          RESERVED1-VAL
          RESERVED1
          FLAGS-VAL
          FLAGS
          ECEFXORLAT-VAL
          ECEFXORLAT
          ECEFYORLON-VAL
          ECEFYORLON
          ECEFZORALT-VAL
          ECEFZORALT
          ECEFXORLATHP-VAL
          ECEFXORLATHP
          ECEFYORLONHP-VAL
          ECEFYORLONHP
          ECEFZORALTHP-VAL
          ECEFZORALTHP
          RESERVED2-VAL
          RESERVED2
          FIXEDPOSACC-VAL
          FIXEDPOSACC
          SVINMINDUR-VAL
          SVINMINDUR
          SVINACCLIMIT-VAL
          SVINACCLIMIT
          RESERVED3-VAL
          RESERVED3
))